stages:
  - build
  - deploy

build-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  before_script:
    - cp schema.prisma _frontend/
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag="$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/_frontend"
      --dockerfile "${CI_PROJECT_DIR}/_frontend/Dockerfile"
      --destination "cr.hera.lan/stash:${tag}"
      --skip-tls-verify-registry "cr.hera.lan"
      --cache=true
      --cache-run-layers
      --cache-copy-layers
  only:
    changes:
      - _frontend/**/*
      - schema.prisma

build-worker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  before_script:
    - cp schema.prisma _worker/
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag="$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/_worker"
      --dockerfile "${CI_PROJECT_DIR}/_worker/Dockerfile"
      --destination "cr.hera.lan/stash-worker:${tag}"
      --skip-tls-verify-registry "cr.hera.lan"
      --cache=true
      --cache-run-layers
      --cache-copy-layers
  only:
    changes:
      - _worker/**/*
      - schema.prisma

build-gatekeeper:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag="$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/_gatekeeper"
      --dockerfile "${CI_PROJECT_DIR}/_gatekeeper/Dockerfile"
      --destination "cr.hera.lan/stash-gatekeeper:${tag}"
      --skip-tls-verify-registry "cr.hera.lan"
      --cache=true
      --cache-run-layers
      --cache-copy-layers
  only:
    changes:
      - _gatekeeper/**/*
      - schema.prisma

build-symlinker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag="$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/_symlinker"
      --dockerfile "${CI_PROJECT_DIR}/_symlinker/Dockerfile"
      --destination "cr.hera.lan/stash-symlinker:${tag}"
      --skip-tls-verify-registry "cr.hera.lan"
      --cache=true
      --cache-run-layers
      --cache-copy-layers
  only:
    changes:
      - _symlinker/**/*

build-tv-client:
  image: electronuserland/builder:latest
  stage: build
  before_script:
    - cd _tv_client
    - npm i -g pnpm
    - apt-get update && apt-get install -y flatpak flatpak-builder
  script:
    - flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub org.freedesktop.Sdk//25.08 org.freedesktop.Platform//25.08
    - pnpm install --frozen-lockfile
    - pnpm run dist:linux-unpacked
    - ls dist/linux-unpacked
    - flatpak-builder --disable-rofiles-fuse --repo=repo --force-clean flatpak-build tv-client.yml
    - flatpak build-export repo flatpak-build
    - flatpak build-bundle repo "dist/TV Client-0.0.1-x86_64.flatpak" ms.ant.stash.tv-client
  artifacts:
    paths:
      - "_tv_client/dist/TV Client-0.0.1-x86_64.flatpak"
      - "_tv_client/repo"
  only:
    changes:
      - _tv_client/**/*

pages:
  stage: deploy
  image: electronuserland/builder:latest
  script:
    - ostree init --mode=archive-z2 --repo=public
    - ostree pull-local --repo=public _tv_client/repo
    - flatpak build-update-repo public --generate-static-deltas
    - |
      cat <<EOF > public/stash.flatpakrepo
      [Flatpak Repo]
      Title=Stash Repository
      Url=${CI_PAGES_URL}
      GPGVerify=false
      EOF
  artifacts:
    paths:
      - public
  needs:
    - build-tv-client
  only:
    changes:
      - _tv_client/**/*
